In [3]:
import pandas as pd
import datetime as date

In [4]:
df=pd.read_csv('/content/drive/MyDrive/youtube/US_youtube_trending_data.csv')

In [5]:
df['publishedAt']=pd.to_datetime(df['publishedAt'])

In [6]:
df['trending_date']=pd.to_datetime(df['trending_date'])

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 199190 entries, 0 to 199189
Data columns (total 16 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   video_id           199190 non-null  object
 1   title              199190 non-null  object
 2   publishedAt        199190 non-null  datetime64[ns, UTC]
 3   channelId          199190 non-null  object
 4   channelTitle       199190 non-null  object
 5   categoryId         199190 non-null  int64
 6   trending_date      199190 non-null  datetime64[ns, UTC]
 7   tags               199190 non-null  object
 8   view_count         199190 non-null  int64
 9   likes              199190 non-null  int64
 10  dislikes           199190 non-null  int64
 11  comment_count      199190 non-null  int64
 12  thumbnail_link     199190 non-null  object
 13  comments_disabled  199190 non-null  bool
 14  ratings_disabled   199190 non-null  bool
 15  description        195049 non-null  object
dtypes: bool(2), datetime64[ns, UTC](2), int64(5), object(7)
memory usage: 21.7+ MB

In [8]:
df['published_year']=df['publishedAt'].dt.year

In [9]:
df['published_month']=df['publishedAt'].dt.month_name()

In [10]:
df.drop(['published_month'],axis=1,inplace=True)

In [11]:
df['trending_year']=df['trending_date'].dt.year

In [12]:
df.columns

Index(['video_id', 'title', 'publishedAt', 'channelId', 'channelTitle',
       'categoryId', 'trending_date', 'tags', 'view_count', 'likes',
       'dislikes', 'comment_count', 'thumbnail_link', 'comments_disabled',
       'ratings_disabled', 'description', 'published_year', 'trending_year'],
      dtype='object')

In [13]:
df['trending_month']=df['trending_date'].dt.month_name()

In [14]:
df

,video_id,title,publishedAt,channelId,channelTitle,categoryId,trending_date,tags,view_count,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,description,published_year,trending_year,trending_month
0,3C66w5Z0ixs,I ASKED HER TO BE MY GIRLFRIEND...,2020-08-11 19:20:14+00:00,UCvtRTOMP2TqYqu51xNrqAzg,Brawadis,22,2020-08-12 00:00:00+00:00,brawadis|prank|basketball|skits|ghost|funny vi...,1514614,156908,5855,35313,https://i.ytimg.com/vi/3C66w5Z0ixs/default.jpg,False,False,SUBSCRIBE to BRAWADIS ▶ http://bit.ly/Subscrib...,2020,2020,August
1,M9Pmf9AB4Mo,Apex Legends | Stories from the Outlands – “Th...,2020-08-11 17:00:10+00:00,UC0ZV6M2THA81QT9hrVWJG3A,Apex Legends,20,2020-08-12 00:00:00+00:00,Apex Legends|Apex Legends characters|new Apex ...,2381688,146739,2794,16549,https://i.ytimg.com/vi/M9Pmf9AB4Mo/default.jpg,False,False,"While running her own modding shop, Ramya Pare...",2020,2020,August
2,J78aPJ3VyNs,I left youtube for a month and THIS is what ha...,2020-08-11 16:34:06+00:00,UCYzPXprvl5Y-Sf0g4vX-m6g,jacksepticeye,24,2020-08-12 00:00:00+00:00,jacksepticeye|funny|funny meme|memes|jacksepti...,2038853,353787,2628,40221,https://i.ytimg.com/vi/J78aPJ3VyNs/default.jpg,False,False,I left youtube for a month and this is what ha...,2020,2020,August
3,kXLn3HkpjaA,XXL 2020 Freshman Class Revealed - Official An...,2020-08-11 16:38:55+00:00,UCbg_UMjlHJg_19SZckaKajg,XXL,10,2020-08-12 00:00:00+00:00,xxl freshman|xxl freshmen|2020 xxl freshman|20...,496771,23251,1856,7647,https://i.ytimg.com/vi/kXLn3HkpjaA/default.jpg,False,False,Subscribe to XXL → http://bit.ly/subscribe-xxl...,2020,2020,August
4,VIUo6yapDbc,Ultimate DIY Home Movie Theater for The LaBran...,2020-08-11 15:10:05+00:00,UCDVPcEbVLQgLZX0Rt6jo34A,Mr. Kate,26,2020-08-12 00:00:00+00:00,The LaBrant Family|DIY|Interior Design|Makeove...,1123889,45802,964,2196,https://i.ytimg.com/vi/VIUo6yapDbc/default.jpg,False,False,Transforming The LaBrant Family's empty white ...,2020,2020,August
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199185,drvPVTMQ8fU,Film Theory: Mario is IMMORTAL! (Super Mario M...,2023-04-23 17:05:07+00:00,UC3sznuotAs2ohg_U__Jzj_Q,The Film Theorists,1,2023-04-30 00:00:00+00:00,Mario|mario movie|super mario bros|super mario...,2475971,109521,0,6203,https://i.ytimg.com/vi/drvPVTMQ8fU/default.jpg,False,False,*SUBSCRIBE to Film Theory!*Don't miss a Film T...,2023,2023,April
199186,0nMgqZtksyc,Aaron Rodgers Has OFFICIALLY Been Traded To Th...,2023-04-24 20:40:51+00:00,UCxcTeAKWJca6XyJ37_ZoKIQ,The Pat McAfee Show,17,2023-04-30 00:00:00+00:00,pat mcafee|podcast|sports|nfl|ncaa|football|fo...,519306,10084,0,1306,https://i.ytimg.com/vi/0nMgqZtksyc/default.jpg,False,False,This is a conversation from The Pat McAfee Sho...,2023,2023,April
199187,X0dLL4uYivE,My First Game In Japan Broke Records,2023-04-23 15:15:01+00:00,UCczKsS4gTjJzU5zayrNnwEA,Trevor Bauer,17,2023-04-30 00:00:00+00:00,[None],1100305,28114,0,1328,https://i.ytimg.com/vi/X0dLL4uYivE/default.jpg,False,False,Get BauerOutage Merch from here 👉 https://www....,2023,2023,April
199188,oWc6RY8U6KQ,MY DAUGHTER'S DREAM VACATION in Alphabetical O...,2023-04-22 14:00:09+00:00,UCKaCalz5N5ienIbfPzEbYuA,Jordan Matter,24,2023-04-30 00:00:00+00:00,jordan matter|salish matter|hudson matter|nali...,7368531,105583,0,72654,https://i.ytimg.com/vi/oWc6RY8U6KQ/default.jpg,False,False,My daughter Salish and son Hudson attempt thei...,2023,2023,April
199189,E9kW_dUlTV0,THE CHAMPIONS! Pitch Invasion & Chest Cam!,2023-04-23 18:55:12+00:00,UCi33DX7KG3M3bI0ipjOP2Eg,Ben Foster - The Cycling GK,17,2023-04-30 00:00:00+00:00,The Cycling GK|English premier league|soccer|B...,1870384,83156,0,6558,https://i.ytimg.com/vi/E9kW_dUlTV0/default.jpg,False,False,Use Code BFCGK at Manscaped.com and get 20% of...,2023,2023,April

In [15]:
js=pd.read_json('/content/drive/MyDrive/youtube/US_category_id.json')

In [16]:
df.head(2)

,video_id,title,publishedAt,channelId,channelTitle,categoryId,trending_date,tags,view_count,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,description,published_year,trending_year,trending_month
0,3C66w5Z0ixs,I ASKED HER TO BE MY GIRLFRIEND...,2020-08-11 19:20:14+00:00,UCvtRTOMP2TqYqu51xNrqAzg,Brawadis,22,2020-08-12 00:00:00+00:00,brawadis|prank|basketball|skits|ghost|funny vi...,1514614,156908,5855,35313,https://i.ytimg.com/vi/3C66w5Z0ixs/default.jpg,False,False,SUBSCRIBE to BRAWADIS ▶ http://bit.ly/Subscrib...,2020,2020,August
1,M9Pmf9AB4Mo,Apex Legends | Stories from the Outlands – “Th...,2020-08-11 17:00:10+00:00,UC0ZV6M2THA81QT9hrVWJG3A,Apex Legends,20,2020-08-12 00:00:00+00:00,Apex Legends|Apex Legends characters|new Apex ...,2381688,146739,2794,16549,https://i.ytimg.com/vi/M9Pmf9AB4Mo/default.jpg,False,False,"While running her own modding shop, Ramya Pare...",2020,2020,August

In [17]:
js.head()

,kind,etag,items
0,youtube#videoCategoryListResponse,HIrK3n45Uw2IYz9_U2-gK1OsXvo,"{'kind': 'youtube#videoCategory', 'etag': 'IfW..."
1,youtube#videoCategoryListResponse,HIrK3n45Uw2IYz9_U2-gK1OsXvo,"{'kind': 'youtube#videoCategory', 'etag': '5XG..."
2,youtube#videoCategoryListResponse,HIrK3n45Uw2IYz9_U2-gK1OsXvo,"{'kind': 'youtube#videoCategory', 'etag': 'HCj..."
3,youtube#videoCategoryListResponse,HIrK3n45Uw2IYz9_U2-gK1OsXvo,"{'kind': 'youtube#videoCategory', 'etag': 'ra8..."
4,youtube#videoCategoryListResponse,HIrK3n45Uw2IYz9_U2-gK1OsXvo,"{'kind': 'youtube#videoCategory', 'etag': '7mq..."

In [18]:
js['items'][0]

{'kind': 'youtube#videoCategory',
 'etag': 'IfWa37JGcqZs-jZeAyFGkbeh6bc',
 'id': '1',
 'snippet': {'title': 'Film & Animation',
  'assignable': True,
  'channelId': 'UCBR8-60-B28hp2BmDPdntcQ'}}

In [19]:
df['categoryId'].unique()

array([22, 20, 24, 10, 26, 27, 23, 28,  1, 25, 17, 19, 15,  2, 29])

In [20]:
js

,kind,etag,items
0,youtube#videoCategoryListResponse,HIrK3n45Uw2IYz9_U2-gK1OsXvo,"{'kind': 'youtube#videoCategory', 'etag': 'IfW..."
1,youtube#videoCategoryListResponse,HIrK3n45Uw2IYz9_U2-gK1OsXvo,"{'kind': 'youtube#videoCategory', 'etag': '5XG..."
2,youtube#videoCategoryListResponse,HIrK3n45Uw2IYz9_U2-gK1OsXvo,"{'kind': 'youtube#videoCategory', 'etag': 'HCj..."
3,youtube#videoCategoryListResponse,HIrK3n45Uw2IYz9_U2-gK1OsXvo,"{'kind': 'youtube#videoCategory', 'etag': 'ra8..."
4,youtube#videoCategoryListResponse,HIrK3n45Uw2IYz9_U2-gK1OsXvo,"{'kind': 'youtube#videoCategory', 'etag': '7mq..."
5,youtube#videoCategoryListResponse,HIrK3n45Uw2IYz9_U2-gK1OsXvo,"{'kind': 'youtube#videoCategory', 'etag': '0Z6..."
6,youtube#videoCategoryListResponse,HIrK3n45Uw2IYz9_U2-gK1OsXvo,"{'kind': 'youtube#videoCategory', 'etag': 'K_-..."
7,youtube#videoCategoryListResponse,HIrK3n45Uw2IYz9_U2-gK1OsXvo,"{'kind': 'youtube#videoCategory', 'etag': 'I3I..."
8,youtube#videoCategoryListResponse,HIrK3n45Uw2IYz9_U2-gK1OsXvo,"{'kind': 'youtube#videoCategory', 'etag': 'D1W..."
9,youtube#videoCategoryListResponse,HIrK3n45Uw2IYz9_U2-gK1OsXvo,"{'kind': 'youtube#videoCategory', 'etag': 'QME..."
10,youtube#videoCategoryListResponse,HIrK3n45Uw2IYz9_U2-gK1OsXvo,"{'kind': 'youtube#videoCategory', 'etag': 'v2n..."
11,youtube#videoCategoryListResponse,HIrK3n45Uw2IYz9_U2-gK1OsXvo,"{'kind': 'youtube#videoCategory', 'etag': 'Qi1..."
12,youtube#videoCategoryListResponse,HIrK3n45Uw2IYz9_U2-gK1OsXvo,"{'kind': 'youtube#videoCategory', 'etag': 'IbG..."
13,youtube#videoCategoryListResponse,HIrK3n45Uw2IYz9_U2-gK1OsXvo,"{'kind': 'youtube#videoCategory', 'etag': 'gYz..."
14,youtube#videoCategoryListResponse,HIrK3n45Uw2IYz9_U2-gK1OsXvo,"{'kind': 'youtube#videoCategory', 'etag': 'hHU..."
15,youtube#videoCategoryListResponse,HIrK3n45Uw2IYz9_U2-gK1OsXvo,"{'kind': 'youtube#videoCategory', 'etag': 'KEd..."
16,youtube#videoCategoryListResponse,HIrK3n45Uw2IYz9_U2-gK1OsXvo,"{'kind': 'youtube#videoCategory', 'etag': 'Aio..."
17,youtube#videoCategoryListResponse,HIrK3n45Uw2IYz9_U2-gK1OsXvo,"{'kind': 'youtube#videoCategory', 'etag': 'tMf..."
18,youtube#videoCategoryListResponse,HIrK3n45Uw2IYz9_U2-gK1OsXvo,"{'kind': 'youtube#videoCategory', 'etag': 'tot..."
19,youtube#videoCategoryListResponse,HIrK3n45Uw2IYz9_U2-gK1OsXvo,"{'kind': 'youtube#videoCategory', 'etag': 'LNg..."
20,youtube#videoCategoryListResponse,HIrK3n45Uw2IYz9_U2-gK1OsXvo,"{'kind': 'youtube#videoCategory', 'etag': 'har..."
21,youtube#videoCategoryListResponse,HIrK3n45Uw2IYz9_U2-gK1OsXvo,"{'kind': 'youtube#videoCategory', 'etag': 'M6Y..."
22,youtube#videoCategoryListResponse,HIrK3n45Uw2IYz9_U2-gK1OsXvo,"{'kind': 'youtube#videoCategory', 'etag': 'ZFb..."
23,youtube#videoCategoryListResponse,HIrK3n45Uw2IYz9_U2-gK1OsXvo,"{'kind': 'youtube#videoCategory', 'etag': 'FD7..."
24,youtube#videoCategoryListResponse,HIrK3n45Uw2IYz9_U2-gK1OsXvo,"{'kind': 'youtube#videoCategory', 'etag': '7fv..."
25,youtube#videoCategoryListResponse,HIrK3n45Uw2IYz9_U2-gK1OsXvo,"{'kind': 'youtube#videoCategory', 'etag': 'H6d..."
26,youtube#videoCategoryListResponse,HIrK3n45Uw2IYz9_U2-gK1OsXvo,"{'kind': 'youtube#videoCategory', 'etag': 'Z3y..."
27,youtube#videoCategoryListResponse,HIrK3n45Uw2IYz9_U2-gK1OsXvo,"{'kind': 'youtube#videoCategory', 'etag': '3F8..."
28,youtube#videoCategoryListResponse,HIrK3n45Uw2IYz9_U2-gK1OsXvo,"{'kind': 'youtube#videoCategory', 'etag': 'Hwu..."
29,youtube#videoCategoryListResponse,HIrK3n45Uw2IYz9_U2-gK1OsXvo,"{'kind': 'youtube#videoCategory', 'etag': 'qJ2..."
30,youtube#videoCategoryListResponse,HIrK3n45Uw2IYz9_U2-gK1OsXvo,"{'kind': 'youtube#videoCategory', 'etag': '2sK..."
31,youtube#videoCategoryListResponse,HIrK3n45Uw2IYz9_U2-gK1OsXvo,"{'kind': 'youtube#videoCategory', 'etag': '3Ia..."

In [21]:
id=[js['items'][i]['id'] for i in range(32)]

In [22]:
id

['1',
 '2',
 '10',
 '15',
 '17',
 '18',
 '19',
 '20',
 '21',
 '22',
 '23',
 '24',
 '25',
 '26',
 '27',
 '28',
 '29',
 '30',
 '31',
 '32',
 '33',
 '34',
 '35',
 '36',
 '37',
 '38',
 '39',
 '40',
 '41',
 '42',
 '43',
 '44']

In [23]:
js['items'][0]

{'kind': 'youtube#videoCategory',
 'etag': 'IfWa37JGcqZs-jZeAyFGkbeh6bc',
 'id': '1',
 'snippet': {'title': 'Film & Animation',
  'assignable': True,
  'channelId': 'UCBR8-60-B28hp2BmDPdntcQ'}}

In [24]:
title=[js['items'][i]['snippet']['title'] for i in range(32)]

In [25]:
title

['Film & Animation',
 'Autos & Vehicles',
 'Music',
 'Pets & Animals',
 'Sports',
 'Short Movies',
 'Travel & Events',
 'Gaming',
 'Videoblogging',
 'People & Blogs',
 'Comedy',
 'Entertainment',
 'News & Politics',
 'Howto & Style',
 'Education',
 'Science & Technology',
 'Nonprofits & Activism',
 'Movies',
 'Anime/Animation',
 'Action/Adventure',
 'Classics',
 'Comedy',
 'Documentary',
 'Drama',
 'Family',
 'Foreign',
 'Horror',
 'Sci-Fi/Fantasy',
 'Thriller',
 'Shorts',
 'Shows',
 'Trailers']

In [26]:
sid=['st1','st2','st3','st4']
sname=['xyz','poq','rst','kmn']

In [27]:
gt=pd.DataFrame({"Student_id":sid,"Student_name":sname,"Address":['lko','hyd','bns','viz']})

In [28]:
new=pd.DataFrame({"categoryId":id,"title_new":title})

In [29]:
new

   categoryId              title_new
0           1       Film & Animation
1           2       Autos & Vehicles
2          10                  Music
3          15         Pets & Animals
4          17                 Sports
5          18           Short Movies
6          19        Travel & Events
7          20                 Gaming
8          21          Videoblogging
9          22         People & Blogs
10         23                 Comedy
11         24          Entertainment
12         25        News & Politics
13         26          Howto & Style
14         27              Education
15         28   Science & Technology
16         29  Nonprofits & Activism
17         30                 Movies
18         31        Anime/Animation
19         32       Action/Adventure
20         33               Classics
21         34                 Comedy
22         35            Documentary
23         36                  Drama
24         37                 Family
25         38                Foreign
26         39                 Horror
27         40         Sci-Fi/Fantasy
28         41               Thriller
29         42                 Shorts
30         43                  Shows
31         44               Trailers

In [30]:
new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   categoryId  32 non-null     object
 1   title_new   32 non-null     object
dtypes: object(2)
memory usage: 640.0+ bytes

In [31]:
new['categoryId']=pd.to_numeric(new['categoryId'])

In [32]:
new.rename(columns={'title_new':'Genre'},inplace=True)

In [33]:
data=pd.merge(df,new,how='inner',on='categoryId')

In [34]:
data.columns

Index(['video_id', 'title', 'publishedAt', 'channelId', 'channelTitle',
       'categoryId', 'trending_date', 'tags', 'view_count', 'likes',
       'dislikes', 'comment_count', 'thumbnail_link', 'comments_disabled',
       'ratings_disabled', 'description', 'published_year', 'trending_year',
       'trending_month', 'Genre'],
      dtype='object')

In [36]:
data[data['video_id']== 'drvPVTMQ8fU']

,video_id,title,publishedAt,channelId,channelTitle,categoryId,trending_date,tags,view_count,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,description,published_year,trending_year,trending_month,Genre
163326,drvPVTMQ8fU,Film Theory: Mario is IMMORTAL! (Super Mario M...,2023-04-23 17:05:07+00:00,UC3sznuotAs2ohg_U__Jzj_Q,The Film Theorists,1,2023-04-25 00:00:00+00:00,Mario|mario movie|super mario bros|super mario...,1822568,92787,0,5374,https://i.ytimg.com/vi/drvPVTMQ8fU/default.jpg,False,False,*SUBSCRIBE to Film Theory!*Don't miss a Film T...,2023,2023,April,Film & Animation
163335,drvPVTMQ8fU,Film Theory: Mario is IMMORTAL! (Super Mario M...,2023-04-23 17:05:07+00:00,UC3sznuotAs2ohg_U__Jzj_Q,The Film Theorists,1,2023-04-26 00:00:00+00:00,Mario|mario movie|super mario bros|super mario...,2045957,98776,0,5569,https://i.ytimg.com/vi/drvPVTMQ8fU/default.jpg,False,False,*SUBSCRIBE to Film Theory!*Don't miss a Film T...,2023,2023,April,Film & Animation
163344,drvPVTMQ8fU,Film Theory: Mario is IMMORTAL! (Super Mario M...,2023-04-23 17:05:07+00:00,UC3sznuotAs2ohg_U__Jzj_Q,The Film Theorists,1,2023-04-27 00:00:00+00:00,Mario|mario movie|super mario bros|super mario...,2167633,101940,0,5737,https://i.ytimg.com/vi/drvPVTMQ8fU/default.jpg,False,False,*SUBSCRIBE to Film Theory!*Don't miss a Film T...,2023,2023,April,Film & Animation
163357,drvPVTMQ8fU,Film Theory: Mario is IMMORTAL! (Super Mario M...,2023-04-23 17:05:07+00:00,UC3sznuotAs2ohg_U__Jzj_Q,The Film Theorists,1,2023-04-28 00:00:00+00:00,Mario|mario movie|super mario bros|super mario...,2253025,104086,0,5869,https://i.ytimg.com/vi/drvPVTMQ8fU/default.jpg,False,False,*SUBSCRIBE to Film Theory!*Don't miss a Film T...,2023,2023,April,Film & Animation
163367,drvPVTMQ8fU,Film Theory: Mario is IMMORTAL! (Super Mario M...,2023-04-23 17:05:07+00:00,UC3sznuotAs2ohg_U__Jzj_Q,The Film Theorists,1,2023-04-29 00:00:00+00:00,Mario|mario movie|super mario bros|super mario...,2355317,106546,0,6029,https://i.ytimg.com/vi/drvPVTMQ8fU/default.jpg,False,False,*SUBSCRIBE to Film Theory!*Don't miss a Film T...,2023,2023,April,Film & Animation
163380,drvPVTMQ8fU,Film Theory: Mario is IMMORTAL! (Super Mario M...,2023-04-23 17:05:07+00:00,UC3sznuotAs2ohg_U__Jzj_Q,The Film Theorists,1,2023-04-30 00:00:00+00:00,Mario|mario movie|super mario bros|super mario...,2475971,109521,0,6203,https://i.ytimg.com/vi/drvPVTMQ8fU/default.jpg,False,False,*SUBSCRIBE to Film Theory!*Don't miss a Film T...,2023,2023,April,Film & Animation

In [37]:
gt=data.groupby('video_id')

In [40]:
video=gt.max()

<ipython-input-40-c61e8c7348fd>:1: FutureWarning: Dropping invalid columns in DataFrameGroupBy.max is deprecated. In a future version, a TypeError will be raised. Before calling .max, select only columns which should be valid for the function.
  video=gt.max()

In [43]:
video.reset_index()

,video_id,title,publishedAt,channelId,channelTitle,categoryId,trending_date,tags,view_count,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,published_year,trending_year,trending_month,Genre
0,--14w5SOEUs,Migos - Avalanche (Official Video),2021-06-10 16:00:00+00:00,UCGIelM2Dj3zza3xyV3pL3WQ,MigosVEVO,10,2021-06-15 00:00:00+00:00,Migos|Avalanche|Quality|Control|Music/Motown|R...,6823249,262692,4107,16445,https://i.ytimg.com/vi/--14w5SOEUs/default.jpg,False,False,2021,2021,June,Music
1,--2O86Z0hsM,MY TESLA PAYS FOR ITSELF,2022-03-09 23:19:08+00:00,UCXJEvxZSozjAAqhbMfhIArA,jf.okay,24,2022-03-15 00:00:00+00:00,[None],538485,17290,0,1439,https://i.ytimg.com/vi/--2O86Z0hsM/default.jpg,False,False,2022,2022,March,Entertainment
2,--40TEbZ9Is,Supporting Actress in a Comedy: 73rd Emmys,2021-09-20 01:03:32+00:00,UClBKH8yZRcM4AsRjDVEdjMg,Television Academy,24,2021-09-25 00:00:00+00:00,[None],682609,8029,369,723,https://i.ytimg.com/vi/--40TEbZ9Is/default.jpg,False,False,2021,2021,September,Entertainment
3,--5-brQiQFg,Washington Commanders vs. San Francisco 49ers ...,2022-12-25 00:30:17+00:00,UCDVYQ4Zhbm3S2dlz7P1GBDg,NFL,17,2022-12-26 00:00:00+00:00,[None],1280997,14603,0,2078,https://i.ytimg.com/vi/--5-brQiQFg/default.jpg,False,False,2022,2022,December,Sports
4,--DKkzWVh-E,Why Retaining Walls Collapse,2021-12-07 13:00:00+00:00,UCMOqf8ab-42UUQIdVoKwjlQ,Practical Engineering,27,2021-12-11 00:00:00+00:00,retaining wall|New Jersey highway|Direct Conne...,623949,29991,320,998,https://i.ytimg.com/vi/--DKkzWVh-E/default.jpg,False,False,2021,2021,December,Education
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36274,zzCrFWjKPy8,Season 1 Episode 3 Preview | House of the Drag...,2022-08-29 02:00:10+00:00,UCQzdMyuz0Lf4zo4uGcEujFw,GameofThrones,22,2022-09-03 00:00:00+00:00,[None],2603821,47431,0,3586,https://i.ytimg.com/vi/zzCrFWjKPy8/default.jpg,False,False,2022,2022,September,People & Blogs
36275,zzd4ydafGR0,Lil Tjay - Calling My Phone (feat. 6LACK) [Off...,2021-02-12 05:03:49+00:00,UCEB4a5o_6KfjxHwNMnmj54Q,Lil Tjay,10,2021-02-21 00:00:00+00:00,Lil Tjay|Steady Calling My Phone|Calling My Ph...,13974461,728439,7579,57012,https://i.ytimg.com/vi/zzd4ydafGR0/default.jpg,False,False,2021,2021,February,Music
36276,zziBybeSAtw,PELICANS at LAKERS | FULL GAME HIGHLIGHTS | Ja...,2021-01-16 05:39:05+00:00,UCWJ2lWNubArHWmf3FIHbfcQ,NBA,17,2021-01-18 00:00:00+00:00,NBA|G League|Basketball|game-0022000187|Lakers...,2598512,20024,989,2872,https://i.ytimg.com/vi/zziBybeSAtw/default.jpg,False,False,2021,2021,January,Sports
36277,zzk09ESX7e0,[MV] 마마무 (MAMAMOO) - Where Are We Now,2021-06-02 09:00:10+00:00,UCuhAUMLzJxlP1W7mEk0_6lA,MAMAMOO,10,2021-06-09 00:00:00+00:00,MAMAMOO|마마무|WAW|마마무 WAW|MAMAMOO WAW|Where Are ...,9389223,584431,3403,77267,https://i.ytimg.com/vi/zzk09ESX7e0/default.jpg,False,False,2021,2021,June,Music
36278,zzsIqPVv2Q4,I Survived 100 DAYS as a SLIME in HARDCORE Min...,2022-04-29 21:45:01+00:00,UCYPYEhWUvvKFgmgkLACagXA,MaxCraft,20,2022-05-05 00:00:00+00:00,maxcraft|minecraft maxcraft|100 days minecraft...,3079200,70776,0,2061,https://i.ytimg.com/vi/zzsIqPVv2Q4/default.jpg,False,False,2022,2022,May,Gaming

In [50]:
pyear=video.groupby('published_year')

In [51]:
pyear.count()

,title,publishedAt,channelId,channelTitle,categoryId,trending_date,tags,view_count,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,trending_year,trending_month,Genre
published_year,,,,,,,,,,,,,,,,,
2020,5276,5276,5276,5276,5276,5276,5276,5276,5276,5276,5276,5276,5276,5276,5276,5276,5276
2021,12969,12969,12969,12969,12969,12969,12969,12969,12969,12969,12969,12969,12969,12969,12969,12969,12969
2022,13918,13918,13918,13918,13918,13918,13918,13918,13918,13918,13918,13918,13918,13918,13918,13918,13918
2023,4116,4116,4116,4116,4116,4116,4116,4116,4116,4116,4116,4116,4116,4116,4116,4116,4116

In [53]:
video['published_year'].value_counts()

2022    13918
2021    12969
2020     5276
2023     4116
Name: published_year, dtype: int64

In [55]:
video.columns

Index(['title', 'publishedAt', 'channelId', 'channelTitle', 'categoryId',
       'trending_date', 'tags', 'view_count', 'likes', 'dislikes',
       'comment_count', 'thumbnail_link', 'comments_disabled',
       'ratings_disabled', 'published_year', 'trending_year', 'trending_month',
       'Genre'],
      dtype='object')

In [97]:
sp=video.groupby('channelTitle')

In [98]:
sp.sum().sort_values(by='view_count',ascending=False)

<ipython-input-98-ddefdb0afda8>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  sp.sum().sort_values(by='view_count',ascending=False)

,categoryId,view_count,likes,dislikes,comment_count,comments_disabled,ratings_disabled,published_year,trending_year
channelTitle,,,,,,,,,
MrBeast,1464,2425110688,144436428,943432,7821923,0,1,123283,123285
BLACKPINK,564,1912983541,149306615,1930077,20193709,0,0,111161,111161
HYBE LABELS,580,1490310158,140341397,538641,24429894,0,0,117265,117265
SMTOWN,660,1369848949,68480544,742517,12539172,0,1,133407,133408
JYP Entertainment,670,1333790001,63455214,609057,11200059,0,0,135440,135441
...,...,...,...,...,...,...,...,...,...
Circle All Access,10,56447,755,8,32,0,0,2020,2020
BW TV,17,46133,302,0,25,0,0,2022,2022
AriAbdulVEVO,10,39598,4635,0,357,0,0,2023,2023
Taleban Dooda,10,35320,1748,0,77,0,0,2023,2023
Doritos,10,0,8994,0,538,0,0,2022,2022

In [99]:
spd=video[video['Genre']=='Sports']

In [100]:
spd.columns

Index(['title', 'publishedAt', 'channelId', 'channelTitle', 'categoryId',
       'trending_date', 'tags', 'view_count', 'likes', 'dislikes',
       'comment_count', 'thumbnail_link', 'comments_disabled',
       'ratings_disabled', 'published_year', 'trending_year', 'trending_month',
       'Genre'],
      dtype='object')

In [101]:
spd.sort_values(by='dislikes',ascending=False)

,title,publishedAt,channelId,channelTitle,categoryId,trending_date,tags,view_count,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,published_year,trending_year,trending_month,Genre
video_id,,,,,,,,,,,,,,,,,,
MbWq-EwUy_M,Dice Stacks from $1 to $100,2021-10-06 21:44:27+00:00,UChfTcl5XfdTUCjkfuro982Q,That's Amazing Shorts,17,2021-10-29 00:00:00+00:00,[None],103564168,7174425,120961,23727,https://i.ytimg.com/vi/MbWq-EwUy_M/default.jpg,False,False,2021,2021,October,Sports
9rhadTURsrw,The Weeknd’s FULL Pepsi Super Bowl LV Halftime...,2021-02-08 01:57:48+00:00,UCDVYQ4Zhbm3S2dlz7P1GBDg,NFL,17,2021-02-17 00:00:00+00:00,Tampa Bay Buccaneers|Kansas City Chiefs|super ...,27865785,1107372,56902,119473,https://i.ytimg.com/vi/9rhadTURsrw/default.jpg,False,False,2021,2021,February,Sports
0F9sX_CHi3g,Impossible iPhone Trick Shot,2021-07-17 16:48:23+00:00,UChfTcl5XfdTUCjkfuro982Q,That's Amazing Shorts,17,2021-07-25 00:00:00+00:00,[None],42683278,2096477,53846,16832,https://i.ytimg.com/vi/0F9sX_CHi3g/default.jpg,False,False,2021,2021,July,Sports
2fsM4KLI7TI,Best Bottle Flippers Challenge,2021-10-03 01:42:38+00:00,UChfTcl5XfdTUCjkfuro982Q,That's Amazing Shorts,17,2021-10-10 00:00:00+00:00,[None],13061150,1317109,37619,4910,https://i.ytimg.com/vi/2fsM4KLI7TI/default.jpg,False,False,2021,2021,October,Sports
OBTs01UT6ec,He threw this into the stratosphere 😱| #Shorts,2021-10-06 02:19:27+00:00,UCQZi2YXSxc6BSK4mZHql8ag,SportsNation,17,2021-10-13 00:00:00+00:00,espn|youtube shorts video|youtube short video|...,32733471,1093592,36015,15808,https://i.ytimg.com/vi/OBTs01UT6ec/default.jpg,False,False,2021,2021,October,Sports
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TSqYrgnbYrY,Extreme Balloon Pop Racing Battle!,2022-05-06 22:00:12+00:00,UC5f5IV0Bf79YLp_p9nfInRA,How Ridiculous,17,2022-05-11 00:00:00+00:00,how ridiculous|rexy|44club,1240347,65689,0,2087,https://i.ytimg.com/vi/TSqYrgnbYrY/default.jpg,False,False,2022,2022,May,Sports
3h6UJl41FRs,2022 FIFA World Cup Draw: Watch the FULL selec...,2022-04-01 18:11:58+00:00,UCooTLkxcpnTNx6vfOovfBFA,FOX Soccer,17,2022-04-07 00:00:00+00:00,fox|fox sports|soccer|fox sports soccer|fox so...,360326,3865,0,1466,https://i.ytimg.com/vi/3h6UJl41FRs/default.jpg,False,False,2022,2022,April,Sports
3gxSv8X9Qbg,SUPER BOWL COSTING PENALTY: Why did Joseph Oss...,2023-01-30 03:06:56+00:00,UC9LrQByjJFCGqUgvylTiVLQ,Jackson Krueger Sports,17,2023-02-05 00:00:00+00:00,nfl|football|sunday|night,284408,1395,0,2134,https://i.ytimg.com/vi/3gxSv8X9Qbg/default.jpg,False,False,2023,2023,January,Sports
TVmHYStY7zQ,Highlights & Goals: Liverpool vs. Man. United ...,2023-03-05 18:32:27+00:00,UCjZ7QPKb89R-4SxzBoceyOg,Telemundo Deportes,17,2023-03-14 00:00:00+00:00,Telemundo Deportes|Liverpool|Manchester United...,749615,8754,0,1277,https://i.ytimg.com/vi/TVmHYStY7zQ/default.jpg,False,False,2023,2023,March,Sports
--5-brQiQFg,Washington Commanders vs. San Francisco 49ers ...,2022-12-25 00:30:17+00:00,UCDVYQ4Zhbm3S2dlz7P1GBDg,NFL,17,2022-12-26 00:00:00+00:00,[None],1280997,14603,0,2078,https://i.ytimg.com/vi/--5-brQiQFg/default.jpg,False,False,2022,2022,December,Sports